; Shortcuts config for dynamic loading
; Hotstrings: ::.api::snippets/api.txt
; Hotkeys: ^!1=snippets/api.txt   (Ctrl+Alt+1)
::.api::snippets/api.txt
::.db::snippets/db.txt
^+1=snippets/azure.txt
^+2=snippets/cloud.txt
^+3=snippets/di.txt
^+4=snippets/ef.txt
^+5=snippets/globalexecptions.txt
^+6=snippets/idempotent.txt
^+7=snippets/jwt
^+8=snippets/keyvault.txt
^+9=snippets/middleware.txt